# Generated by Django 5.0.2 on 2024-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('question', models.TextField(max_length=499)),
                ('priority', models.CharField(choices=[('H', 'high'), ('M', 'medium'), ('L', 'low')], max_length=1)),
            ],
        ),
    ]
